config/routes.rb
RgfNew::Application.routes.draw do

  resources :blogs

  resources :member_attending_event_registers

  root :to => "home#index"

  get "events/update_events"
  get "home/index"
  get "listings/tag/"
  get "listings/add_to_event"
  post 'member_attending_event_registers/accept', :as => 'accept'
  post 'member_attending_event_registers/reject', :as => 'reject'

  resources :mailbox	
  resources :dashboards
  resources :sent

  resources :messages do
   get :reply, :on => :member
   get :forward, :on => :member
   get :reply_all, :on => :member
   put :undelete,  :on => :member
  end

  resources :event_categories
  resources :groups
  resources :profiles

  resources :locations do 
    collection do
        get  :search
    end 
  end

  resources :events do
     member do
       get  :event_attendence
     end
  end
  resources :food_categories
  resources :eat_by_dates
  resources :values
  resources :comments

 resources :listings do
    get :autocomplete_food_category_name, :on => :collection
  collection do
    get  :search
    post :on_offer
  end
 end

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :posts do
    resources :comments
  end

   match "/inbox" => "mailbox#index", :as => :inbox
   match "/sent" => "sent#index", :as => :sent
   match "/trash" => "mailbox#trash", :as => :trash

end

app/models/listing.rb
class Listing < ActiveRecord::Base

 #attr_reader :food_category_name
 #attr_accessible :food_category_name

  geocoded_by :location_address  
  after_validation :geocode  
  after_validation :geocode, :if => :location_address_changed?  

  extend FriendlyId
  friendly_id :title, :use => :slugged

 #Validation =====================================================================================

 #validates_presence_of :title
 #validates_uniqueness_of :title, :message => "Category is alreadey taken"
 #validates_presence_of :food_category_id, :message =>"Please Select A Food Category" 
 #validates_presence_of :location_id, :message => "please Select a location"  
 #validates_presence_of :event_starting_on, :message => "specify a starting date of the event"
 #validates_presence_of :event_ending_on, :message => "Specify an ending date of the event "

#=================================================================================================

 acts_as_taggable_on :tags  #tags definition 

#-================================================================================================

# linking or joining of model 

 belongs_to :user
 belongs_to :food_category
 has_many   :comments, :dependent => :destroy
 belongs_to :profile
 belongs_to :eat_by_date
 belongs_to :location
 has_and_belongs_to_many :values
 has_and_belongs_to_many :events

#==================================================================================================

  has_attached_file :photo,
     :styles  =>
      {
       :icon     =>    "50x50", 
       :thumb    =>    "100x100",
       :profile  =>    "150x150", 
       :small    =>    "400x400>"
      }  


#has_attached_file :photo, :styles => { :small => "150x150>" },
 #                 :url  => "/assets/listings/:id/:style/:basename.:extension",
 #                 :path => ":rails_root/public/assets/listings/:id/:style/:basename.:extension"

validates_attachment_presence :photo
validates_attachment_size :photo, :less_than => 5.megabytes
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

 before_filter :authenticate_user!
 before_filter :tag_count
 #autocomplete :food_category, :name, :full => true


 #autocomplete :food_category, :name do |items|
  #   CustomJSON::Encoder.encode(items)
 #end



  # GET /listings
  # GET /listings.xml
  def index
    @listings = Listing.all
   
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @listings }
    end
  end

  # GET /listings/1
  # GET /listings/1.xml
  def show
    @listing = Listing.find(params[:id])
    @comment = Comment.new(:listing =>@listing)
    @tags = Listing.tag_counts_on(:tags)
    @search  = @listing.location_address
    @search_listing = Listing.find_by_sql("select title from listings where location_address = '#{@search}'")

    #@start_date = @listing.start_date
    #@end_date  = @listing.end_date
    #@total_days = @end_date -Date.today().to_s 
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @listing }
    end
  end 

  # GET /listings/new
  # GET /listings/new.xml
  def new
    @listing = Listing.new
    @values = Value.all

    respond_to do |format|
      format.html # new.html.erb
      format.js
      format.xml  { render :xml => @listing }
    end
  end


#def search 
 #   @listing = Listing.find(params[:id])
 #   @search  = @listing.location_id
    #@search_listing = Listing.find_by_sql("select * from listings where location_id = '#{@search}'")
    
 #   respond_to do |format|
 #     format.html # new.html.erb
 #     format.xml  { render :xml => @listing }
 #   end
 # end


  # GET /listings/1/edit
  def edit
    @listing = Listing.find(params[:id])
    @values = Value.find(:all)
  end

  # POST /listings
  # POST /listings.xml
  def create
    @listing = Listing.new(params[:listing])

    respond_to do |format|
      if @listing.save
        format.html { redirect_to(@listing, :notice => 'Listing was successfully created.') }
        format.xml  { render :xml => @listing, :status => :created, :location => @listing }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @listing.errors, :status => :unprocessable_entity }
      end
    end
  end

#tag cloud

   def tag_cloud
     @tags = Listing.tag_counts_on(:tags)
        logger.info "Tags===> " +@tags.inspect
      #@tags = Listing.tagged_with(params[:id]).page(params[:page])
     # @tags = Listing.tag_counts_on(:tags)
   end

  # PUT /listings/1
  # PUT /listings/1.xml

  def update
    @listing = Listing.find(params[:id])

    respond_to do |format|
      if @listing.update_attributes(params[:listing])
        format.html { redirect_to(@listing, :notice => 'Listing was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @listing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.xml
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to(listings_url) }
      format.xml  { head :ok }
    end
  end

  def tag
	@tag = params[:id]
	@results  = Listing.tagged_with(params[:id])
  end

  def add_to_event
	@listing = Listing.find(params[:id])
	@events = Event.all
  end

  def event_added
	@listing = Listing.find(params[:id])
	respond_to do |format|
        if @listing.save # If save succeeds, redirect to the list action
			flash[:notice] = "Book created"
	        	redirect_to(:action => 'index')
	       else # If save fails, redisplay the form so user can fix problems
	      	      render('add_to_event')
	       end
    end 
  end

end

app/helpers/listings_helper.rb
module ListingsHelper


end

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => {:multipart => true}) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b><%= f.label :title %></b><br />
    <%= f.text_field :title, 
                     :placeholder=>"food listing name",
                     :class=>"inner-inputbox-large",
                     :id=>"textfield" %><br />
  </div><br /><br />

  <div class="field">
    <b><%= f.label :description %></b><br />
    <%= f.text_area :description,
                    :size => "55x10",
                    :class=>"inner-inputarea-large",
                    :id=>"textarea" %>
  </div><br />

  <div class="field">
  <div class="styled-select">
    <b><%= f.label :Select_food_category %></b><br />
       <%= f.collection_select :food_category_id, FoodCategory.find(:all), :id, :name,
                              :class=>"inner-inputbox-large",
                              :id=>"textfield" %>
  </div></div><br />


  <div class="field">
    <b><%= f.label :Listings_address %></b><br />
    <%= f.text_field :location_address,
                     :placeholder=>"Enter listings address",
                     :class=>"inner-inputbox-large",
                     :id=>"textfield" %><br /></td>

  </div><br />

  <div class="field">
    <b><%= f.label :start_date %></b><br />
       <%= f.date_select :start_date %>
  </div><br />


  <div class="field">
    <b><%= f.label :Image_Upload %></b><br />
          <%= f.file_field :photo,
                           :class=>"boton",
                           :id=>"select" %>
  </div>
<br />

  <div class="field">
    <%= f.hidden_field :user_id, :value=>current_user.id %>
  </div>


  <div class="field">
    <b><%= f.label :Food_Type %></b><br />
        <% @values.each do |value| -%>
            <table width="60%" 
                   border="0"
                   cellspacing="0"
                   cellpadding="0"
                   class="inner-inputbox-midum"
                   id="select">
            <tr>

              <td width="14%" height="25" align="left">

                  <%= check_box_tag( 'listing[tag_list][]',
                      value.name,
                      :onClick => "$$('#my_form input.check').each(function(box)
                                     {box.checked=($('check_all').checked)?true:false});")%>
                 <%= value.name %>
              </td>

            </tr>
          </table>
        <% end %>
 </div>
<br />

  <div class="field">
            <table width="60%" 
                   border="0"
                   cellspacing="0"
                   cellpadding="0"
                   class="inner-inputbox-midum"
                   id="select">
            <tr>

   <td width="14%" height="25" align="left">
      <b>
       <%= f.label :Suggested_Storage %>
      </b><br />

    <p><%= f.radio_button  :eat_by_date_id, 1 %>
           <%= f.label :eat_by_date_id, "Shelf" %></p>

    <p><%= f.radio_button  :eat_by_date_id, 2 %>
           <%= f.label :status_2, "Freezer" %></p>
  
    <p><%= f.radio_button  :eat_by_date_id, 3 %>
           <%= f.label :status_3, "Fridge" %></p>
    <br />
  </td>
</tr>
  </div><br />

</table>
<br><br>
  <div class="field">
    <b><%= f.label :end_date %></b><br />
       <%= f.date_select :end_date %>
  </div>
<br />


<br />
  <div class="actions">
    <a>
     <span><%= f.submit :class=>'boton' %></span>
    </a>
   </div>
  </div>

<% end %>

app/views/listings/_search.html.erb
<head>
<style>

.blue, a.blue {
    background: -moz-linear-gradient(center top , #4995CE, #0654A1) repeat scroll 0 0 transparent;
    border: 0px solid #00526F;
    color: #D9EEF7;
    text-shadow: 1px 2px 3px #000000;
}

.button, a.button, 
    #new_comment .submit input, 
    #login_form .submit input {
    border-radius: 0.5em 0.5em 0.5em 0.5em;
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);
    cursor: pointer;
    display: inline-block;
    font: 14px/100% Arial,Helvetica,sans-serif;
    margin: 0 2px;
    outline: medium none;
    text-align: center;
    text-decoration: none;
    text-shadow: 0 1px 1px rgba(0, 0, 0, 0.3);
    vertical-align: baseline;
    width: auto;
}

input {
    font-size: 14px;
    padding: 2px;
}

* {
    margin: 0;
    padding: 0;
}

#search-form
#header #search-form {
}

#header #search-form {
    color: #FFFFFF;
    text-align:left;
    right: 10px;
    top: 10px;
}

#header #feedblitz, #header #search-form {
    border-radius: 0.5em 0.5em 0.5em 0.5em;
    box-shadow: 0 3px 0px #000000;
    padding: 3px;
}
* {
    margin: 0;
    padding: 0;
}
</style>
</head>

<div id="header">
<div id ="search-form">
<%= form_tag search_locations_path, :method => :get, :remote => true do %>
  <%= text_field_tag :search, params[:search],
                     :id => 'search_field',
                     :placeholder =>"find listing enter location name", :size=>'30' %>
  <%= submit_tag "find Listing", :name => nil, :class=>"button blue", :value=>"Go" %> 
<% end %> 
</div>
</div>

app/views/listings/_tag_cloud.html.erb
<% tag_cloud Listing.tag_counts.sort { |x, y| x.name <=> y.name }, %w(css1 css2 css3 css4) do |tag, css_class| %>
   <%= link_to tag.name, value_path(tag ), :class => css_class %>
<% end %>

app/views/listings/add_to_event.html.erb
<p>
<b>Title:</b>
<%= @listing.title %>
</p>

<p>
<b>Food category:</b>
<%= @listing.food_category.name %>
</p>

<p>
<b>Description:</b>
<%= @listing.description %>
</p>

<p>
<b>Start date:</b>
<%= @listing.start_date %>
</p>

<p>
<b>End date:</b>
<%= @listing.end_date %>
</p>

<table>
<b>Food type:</b><br />
<% @listing.tags.each do |f| %>
<tr>
<td><%= f.name %></td>
</tr>
<% end %>
</table>

<p>
<b>Availablity Duration:</b><br />

<% if ( @listing.end_date - Date.today() ).to_i < 0 %>

	<p style = color:darkorange;font-size:20px> <b>"Sorry !..this Listing Has Expired "</b> </p>

<% else %>

	<%= distance_of_time_in_words(Time.now, @listing.end_date +  50.minute) %></td>

	<p style = color:darkorange;font-size:20px> <b> Add To an Event </b> </p>


	<% form_for @listing, {:action => 'event_added', :id => @listing.id} do | f| %>
		<% for event in @events %>
		 	<%= check_box_tag "listing[event_ids][]",  event.id %>
			<%= event.name %>
		<% end %>
		<div class="actions">
		      <a><span><%= f.submit "Add Food to Selected Events" %></span></a>
		</div>

	<% end %>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listing listings</h1>

<table>
  <tr>
    <td><b>Title<hr></b></td>
    <td><b>Food category<hr></b></td>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @listings.each do |listing| %>
  <tr>
    <td><%= listing.title %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td><%= listing.food_category.name %></td>
    <td><%= link_to 'show', listing %></td>
<!--    <td><%= link_to 'Add to Events', {:action => 'add_to_event', :id => listing} %></td>-->
  </tr>
<% end %>
</table>

<br />

<h3><a href="/listings/new" class="button-save-cancel"><span>New Listing</span></a></h3>

app/views/listings/index.js.erb
$("food_categories").update("<%= escape_javascript(render(@food_categories))%>");

app/views/listings/new.html.erb
<%= render 'form' %>

app/views/listings/show.html.erb
<div style ="float:right">
 <% if @listing.user_id == current_user.id %>
  (<%= link_to 'Edit', edit_listing_path(@listing) %> |
  <%= link_to 'Remove', @listing, :confirm => 'Are you sure?', :method => :delete %>)
  <a href="/listings/" class="button-save-cancel"><span>View All Listings</span></a>
<% else %>
  <a href="/listings/" class="button-save-cancel"><span>View All Listings</span></a>
<% end %>
</div>

<div style="height:200px; width:400px; border: 1px solid black;border-radius: 6px;">
<% if @listing.photo.exists? then %>
	<%= image_tag @listing.photo.url, :size =>"400x200" %>
<% end %>
</div>

<br><br>
<p>
<b>Title:</b>
<%= @listing.title %>
</p>
<br>

<p>
<b>Food category:</b>
<%= @listing.food_category.name %>
</p>
<br>

<p>
<b>Description:</b>
<%= @listing.description %>
</p>
<br>

<p>
<b>Start date:</b>
<%= time_tag @listing.start_date %>
</p>
<br>

<p>
<b>End date:</b>
<%= time_tag @listing.end_date %>
</p>
<br>

<table>
<b>Food type:</b><br />
<% @listing.tags.each do |f| %>
<tr>
<td><%= f.name %></td>
</tr>
<% end %>
</table>
<br>

<p>
<b>Availablity Duration:</b>&nbsp;&nbsp;
<% if ( @listing.end_date - Date.today() ).to_i < 0 %>
<p style = color:darkorange;font-size:20px> <b>"Sorry !..this Listing Has Expired "</b> </p>
<% else %>
<%= distance_of_time_in_words(Time.now, @listing.end_date +  50.minute) %></td>
<% end %>
</p>
<br>

<p>
<b>Suggested Storage:</b>
<%= @listing.eat_by_date.name %>
</p>
<hr>

<p>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=14&markers=#{@listing.latitude}%2C#{@listing.longitude}" %>
</p>
<br />


<table cellspacing='0' class="Design4">
<% unless @listing.comments.empty? %>
  <b> 
	<%= pluralize(@listing.comments.size, 'comment') %>
  </b>
  <br>

 <% for comment in @listing.comments %>

<tr>
  <thead>
     <td><%= gravatar_image_tag(current_user.email.downcase,
                                            :alt => current_user.email,
                                            :class => 'gravatar',
                                            :gravatar => {:size => 50}) %>

      <strong style  = color:blue>
         <%= h comment.user.email  %>
     </strong>
      <em>on <%= comment.created_at.strftime('%b %d, %Y at %H:%M') %></em>
<br>
    </td>
</tr>
    <td><%= simple_format comment.content %><hr /></td>
  <% end %>
<% if comment.user_id == current_user.id %>
          <td>&nbsp;&nbsp;&nbsp;<%= link_to 'Edit', edit_comment_path(comment) %></td>
  <% end %>
<% end %>
</table>
<%= render :partial => 'comments/form' %>

app/views/listings/tag.html.erb
<h1><%= @tag %> Food</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Food category</th>
  </tr>

<% @results.each do |listing| %>
  <tr>
    <td><%=link_to listing.title, listing %></td>
    <td><%= link_to listing.food_category.name, listing.food_category %></td>
  </tr>
<% end %>
</table>

<br />

<h3><a href="/listings/new" class="button-save-cancel"><span>New Listing</span></a></h3>