config/routes.rb
RgfNew::Application.routes.draw do

  resources :blogs

  resources :member_attending_event_registers

  root :to => "home#index"

  get "events/update_events"
  get "home/index"
  get "listings/tag/"
  get "listings/add_to_event"
  post 'member_attending_event_registers/accept', :as => 'accept'
  post 'member_attending_event_registers/reject', :as => 'reject'

  resources :mailbox	
  resources :dashboards
  resources :sent

  resources :messages do
   get :reply, :on => :member
   get :forward, :on => :member
   get :reply_all, :on => :member
   put :undelete,  :on => :member
  end

  resources :event_categories
  resources :groups
  resources :profiles

  resources :locations do 
    collection do
        get  :search
    end 
  end

  resources :events do
     member do
       get  :event_attendence
     end
  end
  resources :food_categories
  resources :eat_by_dates
  resources :values
  resources :comments

 resources :listings do
    get :autocomplete_food_category_name, :on => :collection
  collection do
    get  :search
    post :on_offer
  end
 end

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :posts do
    resources :comments
  end

   match "/inbox" => "mailbox#index", :as => :inbox
   match "/sent" => "sent#index", :as => :sent
   match "/trash" => "mailbox#trash", :as => :trash

end

app/models/group.rb
class Group < ActiveRecord::Base
 has_many :users

  has_attached_file :photo,
     :styles  =>
      {
       :icon     =>    "50x50", 
       :thumb    =>    "90x90",
       :profile  =>    "150x150", 
       :small    =>    "400x400>"
      }  


 
 acts_as_gmappable

 def gmaps4rails_address
    location
 end

 def gmaps4rails_infowindow
  "<h4>#{name}</h4>" << "<h4>#{location}</h4>"
 end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.xml
  def index
    @groups = Group.all    

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.xml
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to(@group, :notice => 'Group was successfully created.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to(@group, :notice => 'Group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group, :html => {:multipart => true}) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.hidden_field :group_type , :value =>"public" %>
<!--     <select name="group[group_type]">
       <option>Public</option>
       <option>Private</option>
     </select> -->
  </div>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
   <%= f.label :tags %><br />
   <%= f.text_field :tag %>
  </div>

  <div class="field">
    <%= f.label :'Upload Group Image' %><br />
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/groups/_rightbar.html.erb
<br /><br />
<br /><br />
<div style = "font-size:15px;color:black">

<p>
   New Event <%= link_to image_tag("../images/Add Green Button.png",:size=>"20x20"), new_event_path %><br /><br />
   New Listing <%= link_to image_tag("../images/Add Green Button.png",:size=>"20x20"), new_listing_path %><br /><br />
   New Group <%= link_to image_tag("../images/Add Green Button.png",:size=>"20x20"), new_group_path %><br /><br />
</p>

</div>

app/views/groups/_sidebar.html.erb
<h4> Upcoming Events </h4>
<p>
<div style = "border:0px solid;	font-size:10px">
   <% Event.where(:created_at => 2.days.ago .. 2.days.from_now).each do |e| %>
   <h3><b><%= link_to e.name, e %></b><br />
   Starting On:  <u><%= e.event_starting_on %></u></h3><br />
<% end %> 
</div>
</p>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>All Groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
  </tr>
<% @groups.each do |group| %>
  <tr>
    <td><%= group.name %>
    <td><%= group.location %>

    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'More..', group %></td>
  </tr>
<% end %>
</table>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p>
  <b>Name:</b>
  <%= @group.name %>
</p>

<p>
  <b>Group type:</b>
  <%= @group.group_type %>
</p>

<p>
  <b>Location:</b>
  <%= @group.location %>
</p>

<p>
  <b>Description:</b>
  <%= @group.description %>
</p>

<br><br><br>

<p>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=14&markers=#{@group.latitude}%2C#{@group.longitude}" %>
</p>
<br><br><br>

<div style = "font-size:15px">

  <%= link_to 'Edit', edit_group_path(@group) %> | 
  <%= link_to 'Destroy', @group, :confirm => 'Are you sure?', :method => :delete %> | 
  <%= link_to 'List All Groups', groups_path %> 

</div>