config/routes.rb
RgfNew::Application.routes.draw do

  resources :blogs

  resources :member_attending_event_registers

  root :to => "home#index"

  get "events/update_events"
  get "home/index"
  get "listings/tag/"
  get "listings/add_to_event"
  post 'member_attending_event_registers/accept', :as => 'accept'
  post 'member_attending_event_registers/reject', :as => 'reject'

  resources :mailbox	
  resources :dashboards
  resources :sent

  resources :messages do
   get :reply, :on => :member
   get :forward, :on => :member
   get :reply_all, :on => :member
   put :undelete,  :on => :member
  end

  resources :event_categories
  resources :groups
  resources :profiles

  resources :locations do 
    collection do
        get  :search
    end 
  end

  resources :events do
     member do
       get  :event_attendence
     end
  end
  resources :food_categories
  resources :eat_by_dates
  resources :values
  resources :comments

 resources :listings do
    get :autocomplete_food_category_name, :on => :collection
  collection do
    get  :search
    post :on_offer
  end
 end

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :posts do
    resources :comments
  end

   match "/inbox" => "mailbox#index", :as => :inbox
   match "/sent" => "sent#index", :as => :sent
   match "/trash" => "mailbox#trash", :as => :trash

end

app/views/shared/_footer.html.erb
<div id="footer">
      <%= render :partial => 'listings/tag_cloud' %>
</div>

app/views/shared/_global_links.html.erb
<% if signed_in? %>
 	<strong><%= current_user.email %></strong> | 
	<strong><%= link_to "MY ACCOUNT", edit_user_registration_path %></strong> | 
	<strong><%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete %> | </strong>
	<strong><%= link_to "MY DASHBOARD", dashboard_path(current_user) %> </strong>
<% else %>
        <strong><%= link_to 'REGISTER', new_user_registration_path, :class => "register_link" %></strong> |
	<strong><%= link_to "SIGN IN", user_session_path %></strong>
<% end %>

app/views/shared/_tabs.html.erb
<ul>
  <!--
	<li style="float: right;"><a href="#">Tab 1</a></li>
	<li style="float: right;"><a href="#">Tab 2</a></li>
    -->
	<li><%= tab_to "Post", posts_path %></li>
	<li><%= tab_to "Users", users_path %></li>
	<li><%= tab_to "Comments", comments_path %></li>
	<li><%= tab_to "Users", users_path %></li>
	<li><%= tab_to "Users", users_path %></li>
	<li><%= tab_to "Users", users_path %></li>
	<li><%= tab_to "Users", users_path %></li>
	<li><%= tab_to "Users", users_path %></li>
	<li><%= tab_to "Users", users_path %></li>
	<li><%= tab_to "Users", users_path %></li>

</ul>

app/views/shared/_tag_cloud.html.erb
<% tag_cloud Listing.tag_counts.sort { |x, y| x.name <=> y.name }, %w(css1 css2 css3 css4) do |tag, css_class| %>
<%= link_to tag.name, value_path(tag), :class => css_class %>
<% end %>