config/routes.rb
RgfNew::Application.routes.draw do

  resources :blogs

  resources :member_attending_event_registers

  root :to => "home#index"

  get "events/update_events"
  get "home/index"
  get "listings/tag/"
  get "listings/add_to_event"
  post 'member_attending_event_registers/accept', :as => 'accept'
  post 'member_attending_event_registers/reject', :as => 'reject'

  resources :mailbox	
  resources :dashboards
  resources :sent

  resources :messages do
   get :reply, :on => :member
   get :forward, :on => :member
   get :reply_all, :on => :member
   put :undelete,  :on => :member
  end

  resources :event_categories
  resources :groups
  resources :profiles

  resources :locations do 
    collection do
        get  :search
    end 
  end

  resources :events do
     member do
       get  :event_attendence
     end
  end
  resources :food_categories
  resources :eat_by_dates
  resources :values
  resources :comments

 resources :listings do
    get :autocomplete_food_category_name, :on => :collection
  collection do
    get  :search
    post :on_offer
  end
 end

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :posts do
    resources :comments
  end

   match "/inbox" => "mailbox#index", :as => :inbox
   match "/sent" => "sent#index", :as => :sent
   match "/trash" => "mailbox#trash", :as => :trash

end

app/views/layouts/untitled folder/Final layout/ahome.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Real Good Food</title>
 <%= stylesheet_link_tag 'real-good-food.css','nivo-theme.css','nivo-slider.css','tabmenu.css' %>
  <%= stylesheet_link_tag 'text-expand.css' %>
 <%= javascript_include_tag 'tabmenu.js','jquery-1.4.2.min.js', 'jquery-ui-1.8.2.custom.min.js', 
                            'rails.js', 'autocomplete-rails.js' %>
 <%= stylesheet_link_tag 'jquery-ui-1.8.2.custom.css' %>
 <%= javascript_include_tag :defaults %>
 <%= csrf_meta_tag %>
 <%= yield :head %>
</head>

<body>
 <%= javascript_include_tag 'tabmenu.js' %>
<script type="text/javascript">

$(document).ready(function() {

	//Default Action
	$(".tab_content").hide(); //Hide all content
	$("ul.tabs li:first").addClass("active").show(); //Activate first tab
	$(".tab_content:first").show(); //Show first tab content
	
	//On Click Event
	$("ul.tabs li").click(function() {
		$("ul.tabs li").removeClass("active"); //Remove any "active" class
		$(this).addClass("active"); //Add "active" class to selected tab
		$(".tab_content").hide(); //Hide all tab content
		var activeTab = $(this).find("a").attr("href"); //Find the rel attribute value to identify the active tab + content
		$(activeTab).fadeIn(); //Fade in the active content
		return false;
	});

});
</script>
<div id="sitewrapper">
  <div id="logo-mainwrapper">
   <div class="left"> <a href="index.html"><img src="../images/logo.jpg" width="136" height="123" alt="logo" /></a> </div>
    <div class="logo-right">
<% if signed_in? %>
        <div class="facebook-login-button-main"> 
        <%= link_to current_user.email, profile_path(current_user), :class=>"button-facebook-memberlogin" %>
        <%= link_to "My Account", edit_user_registration_path, :class=>"button-facebook-memberlogin" %>         
	<%= link_to "Log out", destroy_user_session_path, :method => :delete, :class=>"button-facebook-memberlogin" %>
<% else %>      
        <div class="facebook-login-button-main"> 
        <a href="#">Join Now</a> <a href="#" class="button-facebook-memberlogin"><span></span>Connect with Facebook</a>
        <%= link_to 'Create a free account', new_user_registration_path, :class => "register_link" %>        
 	<%= link_to "Member Login", user_session_path, :class=>"button-facebook-memberlogin" %>
<% end %>
 </div>
      <div class="clear"></div>
      <div class="top-nav">
        <span>
          <a href=""><%= link_to 'My Profile', profile_path(current_user) %></a>
          <a href="/listings">All Listings</a>
          <a href="/events">All Events</a>
          <a href="/groups">Groups</a>
          <a href="/">Home</a>
          <a href=""><%= link_to 'My dashboard', dashboards_path %></a>
       </span>
     </div>
    </div>
  </div>
  <div id="header-border">
    <div>
      <div id="wrapper">
        <div class="slider-wrapper nivo-theme">
          <div class="ribbon"></div>
          <div id="slider" class="nivoSlider"> <img src="../images/header.jpg" alt="" /> <img src="../images/header2.jpg" alt="" /> <img src="../images/header3.jpg" alt="" /> </div>
          <div id="htmlcaption" class="nivo-html-caption"> <strong>This</strong> is an example of a <em>HTML</em> caption with <a href="#">a link</a>. </div>
        </div>
      </div>
    </div>
  </div>
  <div id="maincontainer">
    <div id="left-center-container">
      <div class="description">
        <h1>Welcome to Real Good Food !</h1>
        <p> Thanks for visiting! This is the place to be if you love to cook and share your creations with people who will appreciate them as much as you do.</p>
        <p>Please don't hesitate to join the group most local to you: Ann Arbor, Carrboro/Chapel-Hill, Durham. Or please let us know where you would like Real Good Food to launch next by visiting this page.</p>
        <p>Also, we are in a transition period and we are building a new and more functional website.</p>
      </div>
      <div class="clear"></div>
      <div class="menulinkmain"> 
          <a href="listings/new" class="findameal"></a>
        <div class="menu-right-line"> </div>
        <a href="events/" class="postameal"></a>
        <div class="menu-right-line"> </div>
        <a href="groups/" class="gomobile"></a> </div>
      <div class="clear"></div>
      
      
      <div class="tab-container">


<ul class="tabs">
 <li><a href="#tab1"><span>Events</span></a></li>
 <li><a href="#tab2"><span>Group</span></a></li>
  </ul>
    <div class="event-search-bg">
    <span>
      <div class="left">
<%= form_tag events_path, :method => 'get', :id => "products_search" do %>
    <%= text_field_tag :search, params[:search], :class=>"events-inputbox" %>
      </div>
       <div class="right"><a href="#">
          <img src="../images/search-event.png" alt="search icon" /></a></div>
    </span>
      </div>
<% end %>
 <div class="tab_container">

 <div id="tab1" class="tab_content">
<% @event.each do |e| %>
   <div class="tabmenu-contain-main">
    <div class="tabmenu-contain-image">
      <%= image_tag e.photo.url(:thumb) %>
    </div>
       <div class="tabmenu-contain-teaxright">
         <h2><%= link_to e.name, e %></h2>
         <%= e.address %><br />
         From: <%= time_tag e.event_starting_on %><br />
         To: <%= time_tag e.event_ending_on %>
   </div>
 </div>
<% end %> 
    <div class="pagginginarea">
      <%= will_paginate @event, :class=>"paging-text-sel" %>
    </div>

     </div>

      <div id="tab2" class="tab_content">
            <h2>Group</h2>
   <div class="tabmenu-contain-main">
    <div class="tabmenu-contain-image">
      <img src="../images/event-logo.jpg" width="86" height="64" alt="event logo" />
    </div>
       <div class="tabmenu-contain-teaxright">
             <% Group.find(:all).each do |g| %>
               <b><%= link_to g.name, g %></b><br/>
               <strong>Where:</strong><b><%= g.location %></b><br />
               <strong>Group Type:</strong><b><%= g.group_type %></b><br />
             <% end %>
        </div>
      </div>
</div>

</div>
</div>
</div>
    <div id="righ-container">
      <h3>Search New Good Food</h3>
      <div class="right-box-border">
        <div class="right-box-main">
          <div class="googlemap-seare-area">
            <div class="left">
              <input name="" type="text"  class="google-map-inputbox"/>
            </div>
            <div class="right">

                 <a href="#">
                   <img src="../images/search-icon-rightside.png" width="28" height="29" alt="search icon" /></a>
            </div>
          </div>

          <div class="left">
                  <iframe width="231" height="250" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;q=University+of+Michigan,+207+Fletcher+St,+Ann+Arbor,+Washtenaw,+Michigan+48109-1050&amp;aq=&amp;sll=37.926868,-95.712891&amp;sspn=36.344092,79.013672&amp;vpsrc=0&amp;ie=UTF8&amp;geocode=FaIlhQIdZzkC-w&amp;split=0&amp;hq=&amp;hnear=University+of+Michigan,+207+Fletcher+St,+Ann+Arbor,+Michigan+48109-1050&amp;ll=42.280354,-83.740313&amp;spn=0.017526,0.038581&amp;t=m&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;q=University+of+Michigan,+207+Fletcher+St,+Ann+Arbor,+Washtenaw,+Michigan+48109-1050&amp;aq=&amp;sll=37.926868,-95.712891&amp;sspn=36.344092,79.013672&amp;vpsrc=0&amp;ie=UTF8&amp;geocode=FaIlhQIdZzkC-w&amp;split=0&amp;hq=&amp;hnear=University+of+Michigan,+207+Fletcher+St,+Ann+Arbor,+Michigan+48109-1050&amp;ll=42.280354,-83.740313&amp;spn=0.017526,0.038581&amp;t=m&amp;z=14&amp;iwloc=A" style="color:#0000FF;text-align:left">View Larger Map</a></small> 

          </div>
        </div>
      </div>
      <div class="right-box-border">

        <div class="right-box-main"> <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like-box" data-href="https://www.facebook.com/pages/Real-Good-Food/105166229558748" data-width="231" data-show-faces="true" data-stream="false" data-header="false"></div>
</div>
      </div>
      <h3>Follow us</h3>
      <div class="right-box-border">
        <div class="right-box-main"> <a href="#" class="facebook-icon"></a> <a href="#" class="twitter-icon"></a> <a href="#" class="rss-icon"></a> <a href="#" class="myspace-icon"></a> <a href="#" class="delicious-icon"></a> </div>
      </div>
    </div>
  </div>
  <div id="footer">
    <div class="left">
      <div class="logo-footer"><img src="../images/logo-bottom.jpg" width="62" height="54" alt="logo footer" /></div>
      <div class="left">Copyright © 2011 <br />
        Real Good Food.com, <br />
				<%= render :partial => 'shared/footer' %>
				<%= yield :scripts %>
        All rights Reserved</div>
    </div>
    <div class="right"><a href="#">How does it work?</a> | <a href="#">Learn more</a> | <a href="#">Events</a> | <a href="#">Sigh up</a> | <a href="#">Contact us</a></div>
  </div>
  <div class="clear"></div>
</div>
 <%= javascript_include_tag 'jquery-1.6.1.min.js','jquery.nivo.slider.pack.js' %>
<script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
    </script>
    
    
    
</body>
        <%= yield :scripts %>
</html>

app/views/layouts/untitled folder/Final layout/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Real Good Food</title>
  <%= stylesheet_link_tag 'real-good-food.css' %>
  <%= stylesheet_link_tag 'tabmenu-inner.css', :media => 'screen' %>
  <%= stylesheet_link_tag 'nivo-theme.css', :media => 'screen' %>
  <%= stylesheet_link_tag 'nivo-slider.css', :media => 'screen' %>
  <%= stylesheet_link_tag 'tabmenu.css', :media => 'screen' %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css" %>
  <%= javascript_include_tag 'jquery.min.js' %>

  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js",
                             "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js",
                             "application" %>
  <%= csrf_meta_tag %>
  <%= yield :head %>


</head>

<body>
<script type="text/javascript" src="../javascripts/tabmenu.js"></script>
<script type="text/javascript">

$(document).ready(function() {

	//Default Action
	$(".tab_content").hide(); //Hide all content
	$("ul.tabs li:first").addClass("active").show(); //Activate first tab
	$(".tab_content:first").show(); //Show first tab content
	
	//On Click Event
	$("ul.tabs li").click(function() {
		$("ul.tabs li").removeClass("active"); //Remove any "active" class
		$(this).addClass("active"); //Add "active" class to selected tab
		$(".tab_content").hide(); //Hide all tab content
		var activeTab = $(this).find("a").attr("href"); //Find the rel attribute value to identify the active tab + content
		$(activeTab).fadeIn(); //Fade in the active content
		return false;
	});

});
</script>

<div id="sitewrapper">
  <div id="logo-mainwrapper">

    <div class="left"> <a href="index.html">
       <img src="/images/logo.jpg" width="136" height="123" alt="logo" /></a>
    </div>

    <div class="logo-right">
      <div class="facebook-login-button-main">
    <% if signed_in? %>
 	<strong><%= current_user.email %></strong> | 
	<strong><%= link_to "MY ACCOUNT", edit_user_registration_path, :class=>"button-facebook-memberlogin" %></strong> | 
	<strong><%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete %> | </strong>
    <% else %>
         <a href="#">Join Now</a>
         <a href="#" class="button-facebook-memberlogin"><span></span>Connect with Facebook</a>
         <a><%= link_to 'Create a Free Account', new_user_registration_path, :class => "register_link" %></a>
	<a><%= link_to "Member Login", user_session_path, :class=>"button-facebook-memberlogin" %></a>
    <% end %>
      </div>

    </div>

  </div>
</div>

    <div id="center-right-inner-container">
     <%= yield %>
    </div>
    
    
    
</body>
</html>

app/views/layouts/untitled folder/Final layout/profiles.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Real Good Food - <%= yield(:title) || "The Place to Show Cooking Talent" %></title>
  <%= stylesheet_link_tag 'real-good-food.css','tabmenu-inner.css' %>
  <%= stylesheet_link_tag 'text-expand.css' %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css" %>
  <%= javascript_include_tag 'switchcontent.js','switchicon.js' %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js",
                             "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
  <%= csrf_meta_tag %> 
  <%= javascript_include_tag 'jquery.min.js' %>
<script type="text/javascript">

$(document).ready(function(){
$('#tabs div').hide();
$('#tabs div:first').show();
$('#tabs ul li:first').addClass('active');
$('#tabs ul li a').click(function(){ 
$('#tabs ul li').removeClass('active');
$(this).parent().addClass('active'); 
var currentTab = $(this).attr('href'); 
$('#tabs div').hide();
$(currentTab).show();
return false;
});
});
</script>

<%= javascript_include_tag 'switchcontent.js','switchicon.js' %>

</head>

<body>
<div id="sitewrapper">
  <div id="logo-inner-main">
    <div class="logo-inner"><a href="/"><img src="/images/logo.jpg" width="136" height="123" alt="logo" /></a> </div>
    <div class="logo-inner-right">
	<%= render :partial => 'shared/global_links' %>
    </div>
      <div class="clear"></div>
      <ul class="nav-inner-main">
        <li><%= link_to "All Listings", listings_path %></li>
        <li><%= link_to "All Events", events_path %></li>
        <li><%= link_to "All Groups", groups_path %></li>
        <li><%= link_to "My Dashboard", dashboard_path(current_user) %></li>
      </ul>
    </div>
  </div>
  <div id="gutter">&nbsp; </div>
  <div id="maincontainer">
    <div id="left-container">
      <div class="right-box-border">
        <div class="right-box-main">

          <div class="user-iconbg"> 
           <% if @profile.photo.exists? then %>
	     <%= image_tag @profile.photo.url(:profile) %>
           <% end %>
          </div>

          <div class="username-title"><%= @profile.full_name %></div>

          <div>
               <strong>Member Since:</strong>
                      <%= time_tag @profile.created_at %>
               <strong>Last Login:</strong>
                     <%= time_tag @profile.user.last_sign_in_at %>
          </div>
        </div>
      </div>
      <div class="right-box-border">
        <div class="right-box-main">
          <div class="inner-left-right-side-title">User Option</div>
          <ul class="inner-left-right-link">
            <li><a href="my-dashboard.html">My Dashboard</a></li>
            <li class="sel"><a href="my-profile.html">My Profile</a></li>
            <li><a href="change-password.html">Change Password</a></li>
            <li><a href="add-food-listing.html">Add a food listing</a></li>
            <li><a href="add-event.html">Add an event</a></li>
          </ul>
        </div>
      </div>
      <div class="right-box-border">
        <div class="right-box-main">
          <div class="inner-left-right-side-title">Latest Events</div>
          <br />
          August 10, 2011 – Arlington Farmers Market
          2:30 pm, Farmers Markets
          <hr />
          August 10, 2011 – Arlington Farmers Market
          2:30 pm, Farmers Markets
          <hr />
          August 10, 2011 – Arlington Farmers Market
          2:30 pm, Farmers Markets </div>
      </div>
    </div>
    <div id="center-right-inner-container">
     <%= yield %>
    </div>
  <div id="footer">
    <div class="left">
      <div class="logo-footer"><img src="images/logo-bottom.jpg" width="62" height="54" alt="logo footer" /></div>
      <div class="left">Copyright © 2011 <br />
        Real Good Food.com, <br />
        All rights Reserved</div>
    </div>
    <div class="right"><a href="#">How does it work?</a> | <a href="#">Learn more</a> | <a href="#">Events</a> | <a href="#">Sigh up</a> | <a href="#">Contact us</a></div>
  </div>
  <div class="clear"></div>
</div>
<script type="text/javascript" src="js/jquery-1.6.1.min.js"></script> 
<script type="text/javascript" src="js/jquery.nivo.slider.pack.js"></script> 
<script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
		$(".eg-bar").removeAttr("style");
    });
	
	function showContent()
	{
		
	$(".eg-bar").removeAttr("style");	
	}
    </script>
</body>
</html>